return {}
-- return {
--   "whleucka/reverb.nvim",
--   event = "BufReadPre",
--   opts = {
--     player = "mpv", 
--     max_sounds = 20,
--     sounds = {
--       BufRead = { path = "/Users/johann.schneider/dotfiles/Audio/glass_001.ogg", volume = 100 },
--       CursorMovedI = { path = "/Users/johann.schneider/dotfiles/Audio/click_001.ogg", volume = 100 },
--       InsertLeave = { path = "/Users/johann.schneider/dotfiles/Audio/toggle_001.ogg", volume = 100 },
--       ExitPre = { path = "/Users/johann.schneider/dotfiles/Audio/exit.ogg", volume = 100 },
--       BufWrite = { path = "/Users/johann.schneider/dotfiles/Audio/drop_001.ogg", volume = 100 },
--     },
--   },
-- }
